config/routes.rb
 Rails.application.routes.draw do

   root 'home#homepage'
   # get 'home/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create, :edit]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    #there are 7 routes for each object, since you use 'only' dont forget to specify everything.
    resources :listings, 
      controller: "listings", only: [:create, :edit, :update, :new]
      get "/listings" => "listings#create", as: "listings_create"

  end

  resources :listings, 
  controller: "listings", only: [:index, :show]
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
     #to show all this info, need to justtify it in routes using resources
 
  #create custom route for superadmin to be able to verify listing
   post '/listings/:id/verify' => "listings#verify", as: "verify"

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :listings
	

	validates :listing_type, presence: true
	validates :price, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User


#listing management, organize relation of user and listing 
  has_many :listings

  enum role: [:customer, :moderator, :superadmin]

#user management for sign in with omniauth(other site,eg facebook or google)
  has_many :authentications, dependent: :destroy
  def self.create_with_auth_and_hash(authentication, auth_hash)
  	user = self.create!(
  		name: auth_hash["name"],
  		email: auth_hash["extra"]["raw_info"]["email"],
  		password: SecureRandom.hex(5)
  		)
  	 user.authentications << authentication
  	return user 
  end

#grab fb_token to access facebook for user data 
  def fb_token 
  	x = self.authentications.find_by(provider:'facebook')
  	return x.token unless x.nill
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  def allowed?(action:, user:)
  	#implement some code
  end 





end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  	@listings = Listing.all.order(:listing_name).page params[:page]

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # before_action :set_listing, except: [:index_listing, :new, :create]
  before_action :require_login, except: [:show]


  def index
    @listings = Listing.all.order(:city).page(params[:page]).per(10)
  end

  def new
    @listing = current_user.listings.build
      # authorization code
      if current_user.superadmin?
        flash[:notice] = "Sorry. You are not allowed to perform this action."
        return redirect_to root_path, notice: "Sorry. You do not have the permission to verify a property."
      end
      # end authorization code

      # other code to make the new action work!
  end

#use to update room data before run def new
  def create
    @listing = current_user.listings.build(listing_params)
    if @listing.save
      # redirect_to "/users/#{current_user.id}/listing", notice: "Saved Succes"
      # byebug
      redirect_to user_listing_path(current_user.id, @listing.id), notice: "Saved Success"
    else 
      flash[:alert] = @listing.error.full_messages
      render :new
    end 
  end

  def show
    @listing =  Listing.find(params[:id])
    # @photos = @listing.photos
  end 


  #first i ahve to show a verify button whe n i view a specific listing. Show this button
  #only if i am superamind or moderator (upt oyou).
  # u need to create a custom route to go to this verify method below
  # be abel to view a specific listing page
  # inside that, you ahve tubtton to verify listing if you are a superadmin/moderator
  #once u click go the method below and update listing
  def verify
    if current_user.superadmin?
      @listing = Listing.find(params[:id])
      @listing.update(verification: true)
      flash[:notice] = "Verified!!"
      redirect_to listing_path(@listing)
      end
  end


  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
    if @listing.update(listing_params)
      flash[:notice] = "Saved.."
    else 
      flash[:notice] = @listing.errors.full_messages
    end 
    redirect_back(fallback_location: request.referer)
  end

private
  def set_listing
    @listing = Listing.find(params[:id])
  end 

  def listing_params
    params.require(:listing).permit(:listing_name, :listing_type, :number_of_rooms, :city, :price, :wifi, :active, :user_id, :role)
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
	def create_from_omniauth
		auth_hash =request.env["omniauth.auth"]
		authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)

		#if: previously alrady logged in with OAuth
		if authentication.user
		user = authentication.user
		authentication.update_token(auth_hash)
		@next = root_url
		@notice = "Signed in"
		#else: user logs in with OAuth for the first time 
		else 
			user = User.create_with_auth_and_hash(authentication, auth_hash)
			#you are expected to have a path that leads to a page for editing user details
			@next = '/session/edit'
			@notice = "User created. Please confirm or edit details"
		end 

		sign_in(user)
		redirect_to @next, :notice => @notice
	end 
end 
	 

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	# before_action [:show,:edit], show_Users
	# before_action :set_users, only [:show, :edit]

	def create
		user = User.new(user_params)
		if user.save
			redirect_to root_path
		else 
			redirect_to sign_up_path
		end 
	end 

	def show
  		@listings = @user.listings
  	end


  def edit
    @user = current_user
    redirect_to root_path
  end


	

	private 

	def set_users
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end 

	#below here is old method from rails 3 to add column name into clearance user management
	# def user_from_params
	#     email = user_params.delete(:email)
	#     password = user_params.delete(:password)
	#     name = user_params.delete(:name)

	#     Clearance.configuration.user_model.new(user_params).tap do |user|
	#       user.email = email
	#       user.password = password
	#       user.name = name 
	#       end 
	# 	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/home/homepage.html.erb
<head>
  <title>Homepage</title>
  <link rel="stylesheet" type="text/css" href="/css/application.css">   
</head>

<body>


<br><br><br><br><br>

<%= link_to "Listing Index", listings_path %>
<br>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Price</th>
  </tr>


<% @listings.each do |l| %>
  <tr> 
    <td><%= link_to l.listing_name, listing_path(l) %>
      </td>
    <td><%= l.city %></td>
    <td><%= l.price %></td>
    

  </tr>
<% end %>
</table>

<br><br>

<%= paginate @listings %> 
<%= page_entries_info @listings %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PairBnBClone</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application'  %>
  <%= csrf_meta_tag %>
</head>
<body>
  
<ul class="navbar">
    <li id="tagline"><b>PairBnB</b></li>
    <li> <%= link_to 'Home', root_path %></li>
    <li>
      <form method=post action=/users>
      <input id="search_box" type=text placeholder="Search a place" name="user[]">
      </form></li>
    
    <li><% flash.each do |key, value| -%>
        <div id="flash_<%= key %>"><%= value %></div>
        <% end %></li>
    <li><% if signed_in? -%>
          <%=current_user.name.capitalize %>
        <% else -%>
          <%= link_to t(".sign_up"), sign_up_path %>
          <%= link_to "Facebook sign in", "/auth/facebook" %> 
        <% end -%></li>
    <li><% if signed_in? -%>
          <%= link_to "Become a host", new_user_listing_path(current_user.id) %>
          <% end -%>
    <li><% if signed_in? -%>
         <%= button_to "Sign Out", sign_out_path, method: :delete %>
        <% else -%>
          <%= link_to "Sign In", sign_in_path %>
        <% end -%></li>
  </ul>


  
  <%= yield %>
</body>
</html>

app/views/listings/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Create a Nice and Comfort Home for Your Guest</h1>
	</div><br>
	<div class="panel-body">
		<div class="container">
			<!-- since this is nested array, you have to define the first routes and then the second routes, listing is belong to user, so user has to be defined first. -->
			<%= form_for [current_user, @listing], html: {multipart: true} do |f| %>

				<div class="row">
					<div class="form-group">
						<label>Listing Name</label>
						<%= f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control" %>
					</div>
				</div>
					<div class="col-md-4 select">
						<div class="form-group">
							<label>City</label>
          					<%= f.select :city, [["Hanoi", "Hanoi"], ["Jakarta", "Jakarta"], ["Kuala Lumpur", "Kuala Lumpur"], ["Singapore", "Singapore"] ],
        					id: "city", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Listing Type</label>
							<%= f.select :listing_type, [["Apartment","Apartment"], ["Castle","Castle"], ["House","House"], ["Private Room", "Private Room"], ["Tree House", "Tree House" ], ["Villa", "Villa"] ], id: "listing_type", prompt: "Select", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Number of Rooms</label>
							<%= f.select :number_of_rooms, [["1", "1"], ["2", "2"], ["3", "3"], ["4+", "4"]],
          					id: "number_of_rooms", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label>Price</label>
							<div class="input-group">
								<div class="input-group-addon">$
								<%= f.text_field :price, placeholder: "eg. $100", class: "form-group" %></div>
							</div>	
						</div>
					</div>
				</div>

				
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<%= f.check_box :wifi %> WiFi
						</div>
					</div>					
				</div>	
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<%= f.check_box :smoking_room %> Smoking Room
						</div>
					</div>					
				</div>	

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">							
							<span class="btn btn-default btn-file">
							    <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos 
							    <%= file_field_tag "images[]", type: :file, multiple: true %>
							</span>
						</div>		
					</div>
				</div>
				

				<div class="row">
					<div class="form-group">
						<%= f.check_box :active %> Active
					</div>
				</div>

				<div class="actions">
						<%= f.submit "Save", class: "btn btn-primary" %>
				</div>

				<% end %>

		</div>
	</div>
</div>

app/views/listings/amenities.html.erb
<h1>Listing#amenities</h1>
<p>Find me in app/views/listing/amenities.html.erb</p>

app/views/listings/create.html.erb
<h1>Listing#create</h1>
<p>Find me in app/views/listing/create.html.erb</p>
<%= render partial: '/listings/form', object: form %>

app/views/listings/description.html.erb
<h1>Listing#description</h1>
<p>Find me in app/views/listing/description.html.erb</p>

app/views/listings/index.html.erb
<head> 
<tittle>listing index</tittle>
</head>
<br><br><br><br>


<h1> Available Rooms for your booking</h1>
<br><br>
<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Price</th>
  </tr>


<% @listings.each do |l| %>
  <tr> 
    <td><%= link_to l.listing_name, listing_path(l) %>
      </td>
    <td><%= l.city %></td>
    <td><%= l.price %></td>
    
  </tr>
<% end %>
</table>

<%= link_to "Become a host", new_user_listing_path(current_user.id) %>
<br><br>
<%= paginate @listings %> 
<%= page_entries_info @listings %>

app/views/listings/index_listing.html.erb
<h1>Listing#index_listing</h1>
<p>Find me in app/views/listing/index_listing.html.erb</p>

app/views/listings/location.html.erb
<h1>Listing#location</h1>
<p>Find me in app/views/listing/location.html.erb</p>

app/views/listings/new.html.erb
<%= render partial: '/listings/form' %>

app/views/listings/photo_upload.html.erb
<h1>Listing#photo_upload</h1>
<p>Find me in app/views/listing/photo_upload.html.erb</p>

app/views/listings/show.html.erb
this is show listing 

<h3>This is show more</h3>
  <p>Property Name: <%= @listing.listing_name %></p>
  <p>Type: <%= @listing.listing_type %></p>
  <p>Number of Rooms: <%= @listing.number_of_rooms %></p>
  <p>City <%= @listing.city %></p>
  <p>Price per/night: <%= @listing.price %></p>
  <p>Good wifi: <%= @listing.wifi %></p>
  <p>Smoker Friendly: <%= @listing.smoking_room %></p>
  <p><%= @listing.active %></p>

 

<% if current_user.superadmin? %>
 <%= button_to "Verify Listing", verify_path(@listing) %>
<% end %>





  <%= link_to 'Home', root_path %>
  

app/views/listings/update.html.erb
<h1>Listing#update</h1>
<p>Find me in app/views/listing/update.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
  <%= link_to "Sign in with Facebook", "/auth/facebook" %><br/>
</div>